version: '3.8'

# Requires
# Net mariadb-public
# Net traefik-public
# Config php_upload_64M
# Dir /wp_m34/stgwp1/wordpress
# Dir /wp_m34/stgwp1/filebrowser_config
# Secrets   - MARIADB_USER_SECRET - MARIADB_PASSWORD_SECRET 
# NAME required
# DOMAIN required
# WP_VERSION  optional


secrets:
  mariadb-user:
    external: true
    name: ${MARIADB_USER_SECRET}
  mariadb-password:
    external: true
    name: ${MARIADB_PASSWORD_SECRET}

networks:
  db:
    external: true
    name: mariadb-public
  ingress:
    external: true
    name: traefik-public
    
configs:
  php_upload_64M:
    external: true

services:
  wordpress:
    image: wordpress:${WP_VERSION-5.8-php8.0-apache}
    deploy:
      placement:
        constraints:
          - node.labels.gluster.volume == wp_m34
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.stgwp1-wordpress-http.rule=Host(`stgwp1.cloud.saia.ar`) || Host(`www.stgwp1.cloud.saia.ar`)"
        - "traefik.http.routers.stgwp1-wordpress-http.entrypoints=http"
        - "traefik.http.routers.stgwp1-wordpress-http.middleware=https-redirect"
        - "traefik.http.routers.stgwp1-wordpress-https.rule=Host(`stgwp1.cloud.saia.ar`) || Host(`www.stgwp1.cloud.saia.ar`)"
        - "traefik.http.routers.stgwp1-wordpress-https.entrypoints=https"
        - "traefik.http.routers.stgwp1-wordpress-https.tls=true"
        - "traefik.http.routers.stgwp1-wordpress-https.tls.certresolver=le"
        - "traefik.http.services.stgwp1-wordpress.loadbalancer.server.port=${WP_PORT-80}"
    configs:
      - source: php_upload_64M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
    volumes:
      - /wp_m34/stgwp1/wordpress:/var/www/html
    secrets:
      - mariadb-user
      - mariadb-password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER_FILE: /run/secrets/mariadb-user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb-password
      WORDPRESS_DB_NAME: stgwp1-wp
      WORDPRESS_TABLE_PREFIX: stgwp1_
    networks:
      - ingress
      - db
