version: '3.8'

# Requires
# Net mariadb-public
# Net traefik-public
# Config php_upload_64M
# Dir /wp_m34/${NAME}
# Dir /wp_m34/${NAME}/wordpress
# Dir /wp_m34/${NAME}/filebrowser_config
# Secrets   - mariadb-user - mariadb-password

secrets:
  - mariadb-user:
      external: true
  - mariadb-password:
      external: true

networks:
  db:
    external: true
    name: mariadb-public
  ingress:
    external: true
    name: traefik-public
    
configs:
  php_upload_64M:
    external: true

services:
  wordpress:
    image: wordpress:${WP_VERSION-5.8-php8.0-apache}
    deploy:
      placement:
        constraints:
          - node.labels.gluster.volume == wp_m34
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
         #  https router
        - traefik.http.routers.wordpress_${NAME}-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.wordpress_${NAME}-http.entrypoints=http
        - traefik.http.routers.wordpress_${NAME}-http.middleware=https-redirect
        #  https router
        - traefik.http.routers.${NAME}_wordpress-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}_wordpress-https.entrypoints=https
        - traefik.http.routers.${NAME}_wordpress-https.tls=true
        - traefik.http.routers.${NAME}_wordpress-https.tls.certresolver=le
        #services
        - traefik.http.services.${NAME}_wordpress.loadbalancer.server.port=${WP_PORT-80}
    configs:
      - source: php_upload_64M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
    volumes:
      - /wp_m34/${NAME}/wordpress:/var/www/html
    secrets:
      - mariadb-host
      - mariadb-user
      - mariadb-password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER_FILE: /run/secrets/mariadb-user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb-password
      WORDPRESS_DB_NAME: ${NAME}_wordpress
      WORDPRESS_TABLE_PREFIX: ${NAME}_
    networks:
      - ingress
      - db
      
  filebrowser:
    image: hurlenko/filebrowser
    deploy:
      placement:
        constraints:
          - node.labels.gluster.volume == wp_m34
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
         #  https router
        - traefik.http.routers.wordpress_${NAME}-http.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)"
        - traefik.http.routers.wordpress_${NAME}-http.entrypoints=http
        - traefik.http.routers.wordpress_${NAME}-http.middleware=https-redirect
        #  https router
        - traefik.http.routers.wordpress_${NAME}-https.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)"
        - traefik.http.routers.wordpress_${NAME}-https.entrypoints=https
        - traefik.http.routers.wordpress_${NAME}-https.tls=true
        - traefik.http.routers.wordpress_${NAME}-https.tls.certresolver=le
        #services
        - traefik.http.services.wordpress_${NAME}.loadbalancer.server.port=${FB_PORT-80}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - /wp_m34/${NAME}/wordpress:/data/${NAME}
      - /wp_m34/${NAME}/filebrowser_config:/config
    networks:
      - ingress   
  

