version: '3.8'

networks:
  db:
    external: true
    name: mariadb-public
  ingress:
    external: true
    name: traefik-public

volumes:
  filebrowser_data:
  wordpress:
  ssh_vol:
    external: true
    
configs:
  php_upload_64M:
    external: true
services:
  wordpress:
    image: wordpress:${WP_VERSION-5.8-php8.0-apache}
    labels:
      # The labels are useful for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      # Get the routes from http
      - "traefik.http.routers.${NAME}_router.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}_router.entrypoints=web"
        # Redirect these routes to https
      - "traefik.http.middlewares.${NAME}_redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${NAME}_router.middlewares=${NAME}_redirect-to-https@docker"
      # Get the routes from https
      - "traefik.http.routers.${NAME}_router-secured.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}_router-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.${NAME}_router-secured.tls=true"
      - "traefik.http.routers.${NAME}_router-secured.tls.certresolver=myhttpchallenge"
    configs:
      - source: php_upload_64M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${NAME}-usr
      WORDPRESS_DB_PASSWORD: Lkjpoi098
      WORDPRESS_DB_NAME: ${NAME}-wp
      ##WORDPRESS_TABLE_PREFIX: ${NAME}_
    networks:
      - ingress
      - db
      
  filebrowser:
    image: hurlenko/filebrowser
    labels:
      # The labels are useful for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      # Get the routes from http
      - "traefik.http.routers.files_${NAME}_router.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)"
      - "traefik.http.routers.files_${NAME}_router.entrypoints=web"
        # Redirect these routes to https
      - "traefik.http.middlewares.files_${NAME}_redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.files_${NAME}_router.middlewares=files_${NAME}_redirect-to-https@docker"
      # Get the routes from https
      - "traefik.http.routers.files_${NAME}_router-secured.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)"
      - "traefik.http.routers.files_${NAME}_router-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.files_${NAME}_router-secured.tls=true"
      - "traefik.http.routers.files_${NAME}_router-secured.tls.certresolver=myhttpchallenge"
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - wordpress:/data/${NAME}
      - filebrowser_data:/config
    networks:
      - ingress   
  

