version: '3.8'

# Requires
# Net mariadb-public
# Net traefik-public
# Config php_upload_64M
# Secrets   - MARIADB_PASSWORD_SECRET 
# NAME required
# DOMAIN required
# WP_VERSION  optional
# labels on nodes NAME = production 


secrets:
  mariadb-password:
    external: true
    name: ${MARIADB_PASSWORD_SECRET}

volumes:
  wordpress:
  filebrowser_config:

networks:
  db:
    external: true
    name: ${DB_NET}
  ingress:
    external: true
    name: ${INGRESS_NET}
    
configs:
  php_upload_64M:
    external: true

services:
  wordpress:
    image: ${WP_IMAGE}
    deploy:
      resources:
        limits:
          cpus: ${WP_CPU_LIMIT}
          memory: ${WP_MEMORY_LIMIT}
        reservations:
          cpus: ${WP_CPU_RESERVATION}
          memory: ${WP_MEMORY_RESERVATION}
      replicas: ${WP_REPLICAS}
      placement:
        constraints:
          - node.labels.wordpress.production == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME}-wordpress-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-wordpress-http.entrypoints=http
        - traefik.http.routers.${NAME}-wordpress-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-wordpress-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-wordpress-https.entrypoints=https
        - traefik.http.routers.${NAME}-wordpress-https.tls=true
        - traefik.http.routers.${NAME}-wordpress-https.tls.certresolver=le
        - traefik.http.services.${NAME}-wordpress.loadbalancer.server.port=${WP_PORT-80}
    configs:
      - source: php_upload_64M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mariadb-password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${NAME}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb-password
      WORDPRESS_DB_NAME: ${NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX-wp_}
    networks:
      - ingress
      - db
      
  filebrowser:
    image: ${FB_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.wordpress.production == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME}-filebrowser-http.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-http.entrypoints=http
        - traefik.http.routers.${NAME}-filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-filebrowser-https.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-https.entrypoints=https
        - traefik.http.routers.${NAME}-filebrowser-https.tls=true
        - traefik.http.routers.${NAME}-filebrowser-https.tls.certresolver=le
        - traefik.http.services.${NAME}-filebrowser.loadbalancer.server.port=${FB_PORT-8080}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - wordpress:/data/${NAME}
      - filebrowser_config:/config
    networks:
      - ingress   
  

