version: '3.8'

secrets:
  mariadb-password:
    external: true
    name: ${MARIADB_PASSWORD_SECRET}

volumes:
  wordpress:
  filebrowser_config:
  redis:

networks:
  private:
  db:
    external: true
    name: ${DB_NET}
  ingress:
    external: true
    name: ${INGRESS_NET}
  cache:
    external: true
    name: redis_public
    
configs:
  php_upload_128M_memory_limit_1024M:
    external: true
  wp-config-redis:
    external: true
  varnish-wordpress-vcl:
    external: true

services:
  varnish:
    image: varnish:stable
    deploy:
      resources:
        limits:
          cpus: ${WP_CPU_LIMIT}
          memory: ${WP_MEMORY_LIMIT}
        reservations:
          cpus: ${WP_CPU_RESERVATION}
          memory: ${WP_MEMORY_RESERVATION}
      replicas: ${WP_REPLICAS}
      placement:
        constraints:
          - node.labels.wordpress.${NODE_LABEL} == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-varnish-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-varnish-http.entrypoints=http
        - traefik.http.routers.${NAME}-varnish-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-varnish-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-varnish-https.entrypoints=https
        - traefik.http.routers.${NAME}-varnish-https.tls=true
        - traefik.http.routers.${NAME}-varnish-https.tls.certresolver=le
        - traefik.http.services.${NAME}-varnish.loadbalancer.server.port=${WP_PORT-80}
    configs:
      - source: varnish-wordpress-vcl
        target: /etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec 
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
    networks:
      - ingress
      - private
    
  wordpress:
    image: ${WP_IMAGE}
    deploy:
      resources:
        limits:
          cpus: ${WP_CPU_LIMIT}
          memory: ${WP_MEMORY_LIMIT}
        reservations:
          cpus: ${WP_CPU_RESERVATION}
          memory: ${WP_MEMORY_RESERVATION}
      replicas: ${WP_REPLICAS}
      placement:
        constraints:
          - node.labels.wordpress.${NODE_LABEL} == 1
    configs:
      - source: php_upload_128M_memory_limit_1024M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
      - source: wp-config-redis
        target: /var/www/html/wp-config.php
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mariadb-password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${NAME}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb-password
      WORDPRESS_DB_NAME: ${NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX-wp_}
    networks:
      - ingress
      - db
      - private
      
  filebrowser:
    image: ${FB_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.wordpress.${NODE_LABEL} == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-filebrowser-http.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-http.entrypoints=http
        - traefik.http.routers.${NAME}-filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-filebrowser-https.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-https.entrypoints=https
        - traefik.http.routers.${NAME}-filebrowser-https.tls=true
        - traefik.http.routers.${NAME}-filebrowser-https.tls.certresolver=le
        - traefik.http.services.${NAME}-filebrowser.loadbalancer.server.port=${FB_PORT-8080}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - wordpress:/data/${NAME}
      - filebrowser_config:/config
    networks:
      - ingress   
      
  redis:
    image: redis
    deploy:
      placement:
        constraints:
          - node.labels.wordpress.ecommerce == 1
      resources:
        limits:
          cpus: '2'
          memory: 1000M
        reservations:
          cpus: '0.01'
          memory: 100M
    volumes:
      - redis:/data
    networks:
      - private
  

